insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (2, 'CC');
insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (3, 'TI');
insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (4, 'CE');
insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (5, 'NUIP');
insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (1, 'RC');
insert into simedSch.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION) values (6, 'PASAPORTE');
