insert into simedSch.TIPO_USUARIO (ID_TIPO_USUARIO, NOMBRE_TIPO_USUARIO) values (2, 'ADMINISTRADOR');
insert into simedSch.TIPO_USUARIO (ID_TIPO_USUARIO, NOMBRE_TIPO_USUARIO) values (3, 'ESTANDAR');
insert into simedSch.TIPO_USUARIO (ID_TIPO_USUARIO, NOMBRE_TIPO_USUARIO) values (4, 'PREMIUM');
insert into simedSch.TIPO_USUARIO (ID_TIPO_USUARIO, NOMBRE_TIPO_USUARIO) values (1, 'SUPERADMIN');
