
export class LugaresAtencion {
    ID_LUGARES_ATENCION: number
    NOMBRE_LUGAR_ATENCION: string
    DIRECCION_LUGAR_ATENCION: string
    TELEFONO_LUGAR_ATENCION: string
    SITIO_WEB_LUGAR_ATENCION: string
    LATITUD_LUGAR_ATENCION: string
    LONGITUD_LUGAR_ATENCION: string
 


}